// react-js_host/src/App.jsx
import React from 'react';
import ReactDOM from 'react-dom';

import './index.scss';

const App = () => (
  <div className='mt-10 text-3xl mx-auto max-w-6xl'>
    <div>Name: react-js_host</div>
    <div>Framework: react</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
  </div>
);
ReactDOM.render(<App />, document.getElementById('app'));

// solid-js_host/src/App.jsx
import { render } from 'solid-js/web';

import './index.scss';

const App = () => (
  <div class='mt-10 text-3xl mx-auto max-w-6xl'>
    <div>Name: solid-js_host</div>
    <div>Framework: solid-js</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
  </div>
);
render(App, document.getElementById('app'));
